Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Max: 1000
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/For:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/RedundantSelf:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false